// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class gamesids
{
        public const string achievement_otterly_rich = "CgkIk5ethYwbEAIQCA"; // <GPGSID>
        public const string achievement_not_to_fifty = "CgkIk5ethYwbEAIQBw"; // <GPGSID>
        public const string achievement_easter_egg = "CgkIk5ethYwbEAIQBA"; // <GPGSID>
        public const string achievement_wanna_read_the_instructions = "CgkIk5ethYwbEAIQCg"; // <GPGSID>
        public const string achievement_try_again = "CgkIk5ethYwbEAIQAg"; // <GPGSID>
        public const string achievement_paid_homage = "CgkIk5ethYwbEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIk5ethYwbEAIQAQ"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkIk5ethYwbEAIQBg"; // <GPGSID>
        public const string achievement_one_percent = "CgkIk5ethYwbEAIQCQ"; // <GPGSID>
        public const string achievement_try_try_again = "CgkIk5ethYwbEAIQAw"; // <GPGSID>
        public const string leaderboard_urchin_king = "CgkIk5ethYwbEAIQCw"; // <GPGSID>

}

